apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: kube-orders
  name: kube-orders
spec:
  lifecycle: production
  owner: my-team
  type: service
